;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-newline-and-maybe-indent
        kill-region
        kill-sexp
        tagedit-insert-dot
        tagedit-insert-equal
        tagedit-insert-lt
        tagedit-kill
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ido-switch-buffer
        tagedit-insert-gt
        ))
